name: Docs Build and Deploy
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2.3.5
        with:
          persist-credentials: false
      # Build sphinx doc
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      # Pushes to netlify branch. Netlify is listening about changes
      - name: Push to Netlify-docs branch 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: netlify-docs
          folder: docs
          CLEAN: true
