name: Update Homebrew Formula

on:
  release:
    types: [published, edited, released]

jobs:
  homebrew-release:
    runs-on: macOS-latest
    steps:
      - name: Release Homebrew Formula
          uses: garden-io/update-homebrew-action@v1
          with:
            packageName: "diw"
            templatePath: "Formula/diw.rb"
            tapRepo: "marcofaul/homebrew-diw"
            srcRepo: "marcofaul/diw"
            authToken: ${{ secrets.AUTH_TOKEN }}
