name: Update Homebrew Formula
on:
  workflow_run:
    workflows:
      - Create release
    types:
      - completed
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          homebrew-tap: MarcoFaul/homebrew-diw
          formula-name: diw
        env:
          COMMITTER_TOKEN: ${{ secrets.BREW_TOKEN }}
