name: Update Homebrew Formula

on:
  push:
    branches:
      - "main"

jobs:
  homebrew-release:
    runs-on: macos-latest
    steps:
      - name: Release Homebrew Formula
        if: github.event.release.prerelease != true
        uses: garden-io/update-homebrew-action@v1
        with:
          packageName: "diw"
          templatePath: "Formula/diw.rb"
          tapRepo: "MarcoFaul/homebrew-diw"
          srcRepo: "MarcoFaul/diw"
          authToken: "44c60101f1376ccfbc99fdd4cb5d2867d923d4e0"
